variable "name" {
  description = "Base Name for all resources (preferably generated by terraform-null-label)"
  type        = string
  default     = "stackx-network"
}

variable "tags" {
  description = "User specific Tags / Labels to attach to resources (will be merged with module tags)"
  type        = map(string)
  default = {
    "ManagedBy" = "Terraform"
  }
}

variable "rg_name" {
  description = "Name of Azure Resource Group"
  type        = string
}

variable "region" {
  description = "AKS region (e.g. `West Europe`) -> `az account list-locations --output table`"
  type        = string
  default     = "East US"
}

# --------------------------------------------------------------------------
# VPC
# --------------------------------------------------------------------------
variable "vpc_cidr_kubevnet" {
  description = "spoke1-kubevnet Azure Virtual Network VPC CIDR network block (e.g. `10.1.0.0/16`)"
  type        = string
  default     = "10.10.0.0/16"
}

variable "vpc_cidr_hub" {
  description = "hub1-firewalvnet Azure Virtual Network VPC CIDR network block (e.g. `10.1.0.0/16`)"
  type        = string
  default     = "10.20.0.0/16"
}

variable "single_nat_gateway" {
  description = "Should be true if you want to provision a single shared NAT Gateway across all of your private networks"
  type        = bool
  default     = false
}
