name: PR - Terratest

on:
  pull_request:
    paths:
      - 'examples/**'
      - 'tests/**'
      - '**.tf'

jobs:
  terratest:
    name: Terratest
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      AWS_DEFAULT_REGION: eu-central-1
      DNS_ADDRESS: 0 # https://github.com/localstack/localstack/issues/6501
      LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_IN_AUTOMATION: true
    steps:
      - name: Start LocalStack
        id: localstack
        if: env.LOCALSTACK_API_KEY != 'false'
        run: |
          # Workaround: https://github.com/localstack/localstack/pull/6831
          pip install pyOpenSSL --upgrade
          pip install cryptography --upgrade
          # install LocalStack cli
          pip install localstack
          # Make sure to pull the latest version of the image
          docker pull localstack/localstack
          # Start LocalStack in the background
          localstack start -d
          # Wait 30 seconds for the LocalStack container to become ready before timing out
          echo "Waiting for LocalStack startup..."
          localstack wait -t 30
          echo "Startup complete"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Versions
        run: |
          GOLANGVER=$(grep .tool-versions -e "golang" | sed "s/golang \(.*\)/\1/")
          echo "GOLANGVERSION=$GOLANGVER" >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANGVERSION }}

      - name: Download Go modules
        run: |
          cd tests && go mod download

      - name: Terratest
        id: terratest
        run: |
          cd tests && go test -v -count 1 -short -timeout "10m" -parallel 32 `go list ./...`
