name: test-weekly

on:
  # cronjob trigger at 03:00 every monday.
  schedule:
  - cron:  "0 3 * * MON"
  # manual trigger
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  test-weekly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set Versions
        run: |
          TFVER=$(grep .tool-versions -e "terraform" | sed "s/terraform \(.*\)/\1/")
          echo "TFVERSION=$TFVER" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TFVERSION }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Test
        id: test
        run: terraform test -verbose
